# DESCRIPTION
# adds git DVCS to my ubuntu-mc:latest docker image

FROM keithroberts/ubuntu-mc:latest

MAINTAINER Keith Roberts <keith@karsites.net>

# update the cache and install required packages
#
RUN apt-get update && apt-get install -y git
